# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12949f092cc122cf7249d40e537d26cd82d7784a0083f0dadf93c403e62097c918e1c4d77516da2a039a5e3e7ece7eeb5c7150b39c6afa6315726cb5646a21b0

test:
  secret_key_base: 2b0c869085a0bbe9f2a97adb1cc5b072792f5100c2c9ecc510b5d9a64b9547232ca148a7be103cb709c98dede9430230cdbb0025f9a37e8f779e93df77cbdaa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
